
spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/immonet_git/var/h2/recipe;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cookma


logging:
  level:
    com:
      github:
        axonsimple: debug

# Possible values for these keys are `default`, `xstream`, `java`, and `jackson`.
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

mongodb:
  host:
    name: localhost
    port: 27017
    database: axon
